### ISSUE TITLE
Question for Game and Board model

### ISSUE THREAD

**Issue by guiguil81** [chesskit-app/chesskit-swift#36]
Hi !

I found your package and for me it's just a amazing package thank you !

I work on projet and i want to build a basic chessBoard game.
For now i create a Board model and i create a board like board().

But i don't understand why you separate Board class and Game class ? if i want to implement chessBoard game i need to create Board and Game and make move on both ?

I see on Board class you have private isKingInCheck method. But it's private, if i implement a Game and a Board i don't have method for display game state ? like kinIsCheck ok checkmate etc ?

Thanks

**Comment by pdil** [comment]
Hey @guiguil81, thanks!

The reason for the two different objects is `Board` is used to validate the rules and piece movements of a game and represents the state of the game at a given position. This is why it has methods like `legalMoves(for:)` and `move(pieceAt:to:)`.

On the other hand, `Game` manages all the positions in a game and is used so you can navigate between the different positions (forward, backward, variations, etc).

The two exist separately and you can use either as you see fit, it's not necessary to use both in all cases (but you will have to make moves in two different places if you want them to be in sync).

As for game state, you can use the `BoardDelegate` to receive updates when the game ends with checkmate or stalemate (see ` didEnd(with:)`). Unfortunately it does not update when the king is in check but that is a good idea for a future improvement.

**Comment by guiguil81** [comment]
Thanks for answer!

Now I understand the logic between `Board` and `Game` thank you.
Yes, maybe it's a good improvement to see if king is in check haha

Thanks you for this package, and I can't wait to see further improvement!

**Comment by pdil** [comment]
Thank you! I've opened #38 to track that improvement.

**Comment by pdil** [comment]
@guiguil81 by the way, after calling `Board.move(pieceAt:to:)` you can check the `Move` object that is returned to see if the king opposite king is in check. You can do this by checking `move.checkState == .check`. For example if the move was for a white piece this will tell you if the black king is in check.

**Comment by guiguil81** [comment]
I see, but I thinks i can't access on this data because move.checkState is on private no ?

**Comment by pdil** [comment]
Oh yeah you're right, that can probably me made public as well
